export const ADD_CHANNEL = 'ADD_CHANNEL'

export const REMOVE_CHANNEL = 'REMOVE_CHANNEL'

export const ADD_REC_CHANNEL = 'ADD_REC_CHANNEL'

export const REMOVE_REC_CHANNEL = 'REMOVE_REC_CHANNEL'

export const ADD_LOCAL_CHANNEL = 'ADD_LOCAL_CHANNEL'

export const REMOVE_LOCAL_CHANNEL = 'REMOVE_LOCAL_CHANNEL'
